name: Symfony

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy env
        run: cp .env.dist .env
    
      - name: docker Build and push
        uses: docker/build-push-action@v2
        timeout-minutes: 10
        with:
          context: .
          file: deploy/docker/Dockerfile.run
          push: true
