name: Symfony

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: docker Build
        uses: docker/setup-buildx-action@v2
        timeout-minutes: 10
        with:
          context: .
          file: deploy/docker/Dockerfile.run
        
      - name: Copy env
        run: cp .env.dist .env
