name: Symfony

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: dev
    steps:    
      - name: Copy env
        run: cp .env.dist .env
